Repository magalhaesm/minishell, pull requests merged in 2023-01, with the labels that each got.

#54 feat(expander): expand environment variables
  Makefile
  include/builtins.h
  include/exec.h
  include/expansion.h
  include/helpers.h
  include/tree.h
  src/builtins/cd.c
  src/builtins/exit.c
  src/builtins/export.c
  src/builtins/unset.c
  src/exec/exec.c
  src/exec/exec_cmd.c
  src/exec/exec_redir.c
  src/exec/exit_status.c
  src/expansion/exp_utils.c
  src/expansion/expand.c
  src/expansion/quotes.c
  src/expansion/wildcard_utils.c
  src/helpers/path.c
  src/helpers/string.c
  src/minishell.c
  src/parser/parser.c
  src/parser/syntax_error.c
  src/parser/tree.c
  src/parser/tree_utils.c
  tests/Makefile
  tests/test_expander.c
  tests/test_parser.c
  tests/test_path.c
  tests/test_quotes.c
  tests/test_string.c
Labels: feature

#55 fix(export): handle invalid names
  src/builtins/export.c
  tests/test_export.c
Labels: bug

#60 fix(list): breaks when it has alternating operators
  src/exec/exec_list.c
  src/parser/grammar/rules1.c
  tests/test_parser.c
Labels: bug

#61 Feature/pwd unset exit builtins
  include/sig_func.h
  src/signals/sig_setup.c
Labels: enhancement

#62 feat(heredoc): implement here-document
  Makefile
  include/exec.h
  include/expansion.h
  include/minishell.h
  src/exec/exec.c
  src/exec/exec_heredoc.c
  src/expansion/quotes.c
Labels: feature

#64 feat(subshell): add parenthesis for priorities
  Makefile
  include/exec.h
  src/exec/exec.c
  src/exec/exec_cmd.c
  src/exec/exec_subshell.c
Labels: feature

#63 feat(heredoc): add signals enhancements
  Makefile
  include/events.h
  include/exec.h
  include/expansion.h
  include/minishell.h
  src/builtins/exit.c
  src/builtins/export.c
  src/exec/exec.c
  src/exec/exec_heredoc.c
  src/exec/exec_redir.c
  src/exec/exec_subshell.c
  src/exec/exit_utils.c
  src/exec/heredoc_utils.c
  src/expansion/exp_utils.c
  src/expansion/expand.c
  src/expansion/quotes.c
  src/signals/events.c
  src/signals/handlers.c
  tests/Makefile
  tests/test_exit.c
  tests/test_quotes.c
Labels: bug, enhancement

#70 fix(expander): replace all strings
  src/helpers/string.c
  tests/test_string.c
Labels: bug

#71 fix(unset): segfault when unsetting the first env
  src/exec/exec_heredoc.c
  src/helpers/environ2.c
Labels: bug

#72 fix(heredoc): fd leak when running without a command
  src/exec/exec_heredoc.c
Labels: bug

#73 fix(pipe): fork builtin functions when on a pipeline
  Makefile
  include/exec.h
  src/exec/exec.c
  src/exec/exec_builtin.c
  src/exec/exec_cmd.c
  src/exec/exec_pipe.c
Labels: bug

#74 Docs/readme wiki
  README.md
  src/minishell.c
Labels: documentation, feature

#75 fix(pipe): use array to avoid leaks when creating pipelines
  include/exec.h
  src/exec/exec.c
  src/exec/exec_cmd.c
  src/exec/exec_list.c
  src/exec/exec_pipe.c
  src/exec/exec_utils.c
Labels: enhancement

#76 fix(return): get the status code from errors
  src/exec/exec.c
Labels: bug

#77 fix: final fixes
  docs/grammar.y
  src/exec/exec.c
  src/exec/exec_cmd.c
Labels: bug

#78 docs: add 7th revision of README
  README.md
Labels: documentation
